"""create profession area and vacancy grade

Revision ID: 137fa99ed4b8
Revises: 4aaab0c9107d
Create Date: 2019-11-05 22:26:54.872203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '137fa99ed4b8'
down_revision = '4aaab0c9107d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prof_areas',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('area_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vacancy_grades',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('vacancy_id', sa.Integer(), nullable=False),
                    sa.Column('prof_area_id', sa.Integer(), nullable=False),
                    sa.Column('grade', sa.DECIMAL(
                        precision=18, scale=17), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['prof_area_id'], ['prof_areas.id'], ),
                    sa.ForeignKeyConstraint(
                        ['vacancy_id'], ['vacancies.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies_grade')
    op.drop_table('prof_areas')
    # ### end Alembic commands ###
