"""refactor4

Revision ID: 46344b77a539
Revises: 0138378f7659
Create Date: 2019-11-02 11:28:22.945581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46344b77a539'
down_revision = '0138378f7659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assoc_skill_category',
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], )
    )
    op.create_table('assoc_skill_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc_skill_user')
    op.drop_table('assoc_skill_category')
    # ### end Alembic commands ###
