"""create statistic table

Revision ID: 4aaab0c9107d
Revises: a88f0ab2bbb8
Create Date: 2019-11-04 08:37:53.898818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4aaab0c9107d'
down_revision = 'a88f0ab2bbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('vacancy_count', sa.Integer(), nullable=True),
                    sa.Column('languages', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic')
    # ### end Alembic commands ###
