"""base migration

Revision ID: a88f0ab2bbb8
Revises:
Create Date: 2019-11-03 10:45:08.114866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a88f0ab2bbb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=80), server_default='Имя', nullable=True),
    sa.Column('last_name', sa.String(length=80), server_default='Фамилия', nullable=True),
    sa.Column('city', sa.String(length=80), server_default='Город', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_url', sa.TEXT(), nullable=True),
    sa.Column('vacancy_name', sa.TEXT(), nullable=True),
    sa.Column('vacancy_city', sa.String(length=50), nullable=True),
    sa.Column('vacancy_country', sa.String(length=10), nullable=True),
    sa.Column('vacancy_salary_value', sa.TEXT(), nullable=True),
    sa.Column('vacancy_salary_min', sa.TEXT(), nullable=True),
    sa.Column('vacancy_salary_max', sa.TEXT(), nullable=True),
    sa.Column('vacancy_salary_currency', sa.TEXT(), nullable=True),
    sa.Column('vacancy_salary_period', sa.TEXT(), nullable=True),
    sa.Column('company_name', sa.TEXT(), nullable=True),
    sa.Column('vacancy_expirience', sa.TEXT(), nullable=True),
    sa.Column('vacancy_employment_type', sa.TEXT(), nullable=True),
    sa.Column('vacancy_text_clean', sa.TEXT(), nullable=True),
    sa.Column('vacancy_text_en', sa.TEXT(), nullable=True),
    sa.Column('vacancy_key_skills', sa.TEXT(), nullable=True),
    sa.Column('industry', sa.TEXT(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('vacancy_published_at', sa.TEXT(), nullable=True),
    sa.Column('vacancy_graded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assoc_skill_category',
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], )
    )
    op.create_table('assoc_skill_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('favourite_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite_vacancies')
    op.drop_table('assoc_skill_user')
    op.drop_table('assoc_skill_category')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('categories')
    # ### end Alembic commands ###
