"""create assos area users and update columns

Revision ID: bb044280ada3
Revises: a4f024d8b298
Create Date: 2019-11-08 21:02:45.513422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb044280ada3'
down_revision = 'a4f024d8b298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assoc_area_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['prof_areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('vacancies', sa.Column('vacancy_prof_area', sa.Integer(), nullable=True))
    op.add_column('prof_areas', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'vacancy_prof_area')
    op.drop_column('skills', 'count')
    op.drop_column('prof_areas', 'count')
    op.drop_table('assoc_area_user')
    # ### end Alembic commands ###
